version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  store:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: leggodt
      POSTGRES_USER: leggodt
      POSTGRES_PASSWORD: nopwd
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: library/adminer:latest
    restart: always
    ports:
      - 7777:8080
        
volumes:
  postgres: ~
  cache:
    driver: local