# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - leg-godt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Test with dotnet
        env:
          REDIS_HOST: localhost
          REDIS_PASSWORD: ""
        run: |
          dotnet test
          
          dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
          
          livingdoc test-assembly SpecFlowLegGodt/bin/Debug/net6.0/SpecFlowLegGodt.dll -t SpecFlowLegGodt/bin/Debug/net6.0/TestExecution.json
          
          ls .

      - name: Upload livingdoc for gh-pages
        uses: actions/upload-artifact@v2
        with: 
          name: livingdoc
          path: .

  livingdoc:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Upload livingdoc to gh-pages
        uses: actions/upload-artifact@v2
        with:
          name: livingdoc
          path: .

  build:
    runs-on: windows-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  gh-pages:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: livingdoc

      - name: List files
        run: |
          ls .

          mv LivingDoc.html index.html


      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'leg-godt'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D2B5A522F861461E951E2F595AEB159D }}
          package: .
